source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'bootstrap-sass'
gem 'selectize-rails', '~> 0.12.1'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem 'mini_magick'
gem 'sorcery'
gem 'simple_form'
gem 'carrierwave'
gem 'active_type'
gem 'dropzonejs-rails'
gem 'jquery-form-rails'
gem 'russian'
gem 'unicorn'
gem 'mailgun_rails'
gem 'pundit'
gem 'better_errors'
gem 'react-rails'
gem 'airbrake'
gem 'nokogiri'
gem 'activeadmin', github: 'activeadmin'
gem 'acts_as_votable'
gem 'acts_as_follower'
gem 'react-bootstrap-rails'
gem 'destroyed_at'
gem 'migration_data'
gem 'browserify-rails'
gem 'slim-rails'
gem 'omniauth'
gem 'omniauth-vkontakte'
gem 'vkontakte_api', '~> 1.4'
#gem 'carrierwave-imageoptimizer'

group :development, :test do
  gem 'awesome_print'
  gem 'byebug'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'pry-rails'
end

group :development do
  gem 'capistrano-rails-console'
  gem 'capistrano3-unicorn'
  gem 'capistrano-rbenv'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'guard-rails'
end
